#!/bin/sh

usage="$(basename "$0"): generate a disambiguated weightlist using a word2vec model
USAGE: $(basename "$0") [-h] corpus corpus_w2v word2vec_model output_weightlist default_weightlist
corpus	a raw corpus file
corpus_w2v  a large raw corpus file for training the word2vec model
input_file	the input compiled dictionary (a finite state transducer)
word2vec_model	the name of the word2vec model
output_weightlist	a weightlist for unambiguous words in corpus
default_weightlist	a laplace smoothed weightlist for OOV words

Options:
    -h, --help:	show this help
"

while :; do
    case $1 in
        -h|-\?|--help)
            printf "$usage"
            exit
            ;;
        --is_c_format_bin)
            IS_C_FORMAT_BIN="SET"
            ;;
        --is_wiki_dump)
            IS_WIKI_DUMP="SET"
            ;;
        -size)
            SIZE="$2"
            shift
            ;;
        -window)
            WINDOW="$2"
            shift
            ;;
        --)
            shift
            break
            ;;
        -?*)
            printf "WARN: Unknown option (ignored): %s\n" "$1" >&2
            ;;
        *)
            break
    esac

    shift
done

CORPUS=$1
CORPUS_W2V=$2
INPUT_FST=$3
WORD2VEC_MODEL=$4
OUTPUT_WEIGHTLIST=$5
DEFAULT_WEIGHTLIST=$6

no_of_missing_args=0
if [ ! -f "$CORPUS" ]
then
	printf "ERROR: corpus_file \"%s\" doesn't exist\n" "$CORPUS" >&2
	no_of_missing_args=$((no_of_missing_args + 1))
fi

if [ ! -f "$CORPUS_W2V" ]
then
    printf "ERROR: corpus_w2v \"%s\" doesn't exist\n" "$CORPUS_W2V" >&2
    no_of_missing_args=$((no_of_missing_args + 1))
fi

if [ ! -f "$INPUT_FST" ]
then
	printf "ERROR: input_file \"%s\" doesn't exist\n" "$INPUT_FST" >&2
	no_of_missing_args=$((no_of_missing_args + 1))
fi

if [ -z "$WORD2VEC_MODEL" ]
then
	printf "ERROR: word2vec_model isn't set\n" >&2
	no_of_missing_args=$((no_of_missing_args + 1))
fi

if [ -z "$OUTPUT_WEIGHTLIST" ]
then
	printf "ERROR: output_weightlist isn't set\n" >&2
	no_of_missing_args=$((no_of_missing_args + 1))
fi

if [ -z "$DEFAULT_WEIGHTLIST" ]
then
	printf "ERROR: default_weightlist isn't set\n" >&2
	no_of_missing_args=$((no_of_missing_args + 1))
fi

if [ $no_of_missing_args -gt 0 ]
then
	printf "$usage"
	exit
fi

TEMP_DIR=$(mktemp -d)
WORD_FILE="$TEMP_DIR/word"
SIMILAR_WORD_FILE="$TEMP_DIR/similar"

if [ ! -f "$WORD2VEC_MODEL" ]
then
    echo "Training a word2vec model"
    #Initialize pythonhashseed for word2vec reproducilibilty
    if [ -z "$IS_WIKI_DUMP" ]
    then
        PYTHONHASHSEED=42  w2v_train_model.py --corpus_word2vec "$CORPUS_W2V" --word2vec_model "$WORD2VEC_MODEL" -size "$SIZE" -window "$WINDOW"
    else
        PYTHONHASHSEED=42  w2v_train_model.py --corpus_word2vec "$CORPUS_W2V" --word2vec_model "$WORD2VEC_MODEL" -size "$SIZE" -window "$WINDOW" --is_wiki_dump
    fi
fi

# On loading model, used this flag --is_c_format_bin
if [ -z "$IS_C_FORMAT_BIN" ]
then
    w2v_get_similar_words.py --corpus "$CORPUS" --output_words_file "$WORD_FILE" --output_similar_words_file "$SIMILAR_WORD_FILE" --word2vec_model "$WORD2VEC_MODEL"
else
    w2v_get_similar_words.py --corpus "$CORPUS" --output_words_file "$WORD_FILE" --output_similar_words_file "$SIMILAR_WORD_FILE" --word2vec_model "$WORD2VEC_MODEL" --is_c_format_bin
fi

ANALYZED_WORDS="$TEMP_DIR/analyzed_words"
ANALYZED_SIMILAR_WORDS="$TEMP_DIR/analyzed_similar_words"

apertium-destxt "$WORD_FILE" | lt-proc "$INPUT_FST" | apertium-retxt > "$ANALYZED_WORDS"
apertium-destxt "$SIMILAR_WORD_FILE" | lt-proc "$INPUT_FST" | apertium-retxt > "$ANALYZED_SIMILAR_WORDS"

# TODO: WHY?
CLEANED_WORDS="$TEMP_DIR/cleaned_words"
apertium-cleanstream -n < "$ANALYZED_WORDS" > "$CLEANED_WORDS"

w2v_generate_weights_sgt.py --words_file "$CLEANED_WORDS" --similar_file "$ANALYZED_SIMILAR_WORDS" --output_weightlist "$OUTPUT_WEIGHTLIST" --default_weightlist "$DEFAULT_WEIGHTLIST"
